name: Deploy Dashboard
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test
      run: pytest tests/
    - name: Build Docker
      run: docker build -t backtest-lab:latest .
    # Optionally add step to push to Render/AWS/ECR